infantry-build:
	cmake --build cmake-build-debug --target TR-Infantry -j $(nproc)

testbench-build:
	cmake --build cmake-build-debug --target TR-TestBench -j $(nproc)

hero-build:
	cmake --build cmake-build-debug --target TR-Hero -j $(nproc)

sentry-build:
	cmake --build cmake-build-debug --target TR-Sentry -j $(nproc)

infantry: infantry-build
	powershell.exe /c cp cmake-build-debug/robots/Infantry/TR-Infantry.bin D:

testbench: testbench-build
	powershell.exe /c cp cmake-build-debug/robots/TestBench/TR-TestBench.bin D:

hero: hero-build
	powershell.exe /c cp cmake-build-debug/robots/Hero/TR-Hero.bin D:

sentry: sentry-build
	powershell.exe /c cp cmake-build-debug/robots/Sentry/TR-Sentry.bin D:

infantry-pi: infantry-build
	scp cmake-build-debug/robots/Infantry/TR-Infantry.bin pi:/media/anshal/NOD_F446RE

testbench-pi: testbench-build
	scp cmake-build-debug/robots/TestBench/TR-TestBench.bin pi:/media/anshal/NOD_F446RE

hero-pi: hero-build
	scp cmake-build-debug/robots/Hero/TR-Hero.bin pi:/media/anshal/NOD_F446RE

sentry-pi: sentry-build
	scp cmake-build-debug/robots/Sentry/TR-Sentry.bin pi:/media/anshal/NOD_F446RE2

serial:
	powershell.exe /c mbed-tools sterm -b 115200

bind:
	cmd.exe /c usbipd attach --wsl --busid 2-2

mount:
	sudo mount E: /mnt/e