name: Build example application

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs: 
  build-cli-v1:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F446RE]
        profile: [debug]
        

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
          
      -
        name: build-example
        run: |
          set -e
          cd Infantry
          mbed deploy
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
          